name: Automatikus Adatfrissítés

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Budapest'
    permissions:
      contents: write

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Python környezet beállítása
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Csomagok telepítése
        run: pip install -r requirements.txt

      - name: Adatgyűjtő futtatása
        run: python data_collector.py

      - name: Frissített adatbázis feltöltése
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatikus frissítés: új energia és időjárás adatok"
          file_pattern: 'energy_data.db'
