name: Automatikus Adatfrissítés

on:
  schedule:
    
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Budapest'
    permissions:
      contents: write 

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python környezet beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Csomagok telepítése
        run: pip install -r requirements.txt

      - name: Adatgyűjtő futtatása
        run: python data_collector.py

      - name: Frissített adatbázis feltöltése a GitHubra
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add energy_data.db
          git commit -m "Automatikus frissítés: új energia és időjárás adatok" || echo "Nincs új adat"
          git pull --rebase origin main
          git push
